apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: harvester-csi-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: harvester-csi-plugin
  template:
    metadata:
      labels:
        app: harvester-csi-plugin
    spec:
      containers:
        - args:
            - --v=5
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=/var/lib/kubelet/harvester-plugins/driver.harvesterhci.io/csi.sock
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          image: longhornio/csi-node-driver-registrar:v1.2.0-lh1
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - rm -rf /registration/driver.harvesterhci.io-reg.sock
                    /csi//*
          name: node-driver-registrar
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi/
              name: socket-dir
            - mountPath: /registration
              name: registration-dir
        - args:
            - --nodeid=$(NODE_ID)
            - --endpoint=$(CSI_ENDPOINT)
            - --drivername=driver.harvesterhci.io
            - --namespace=default
            - --kubeconfig=/etc/csi/cloud-provider-config
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          image: rancher/harvester-csi-driver:master-head
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - rm -f /csi//*
          name: harvester-csi-plugin
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
          volumeMounts:
            - name: cloud-config
              mountPath: "/etc/csi"
              readOnly: true
            - mountPath: /var/lib/kubelet/plugins/kubernetes.io/csi
              mountPropagation: Bidirectional
              name: kubernetes-csi-dir
            - mountPath: /csi/
              name: socket-dir
            - mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
              name: pods-mount-dir
            - mountPath: /dev
              name: host-dev
            - mountPath: /sys
              name: host-sys
            - mountPath: /rootfs
              mountPropagation: Bidirectional
              name: host
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
      hostPID: true
      serviceAccountName: harvester-csi
      tolerations:
        - effect: NoSchedule
          key: kubevirt.io/drain
          operator: Exists
      volumes:
        - name: cloud-config
          secret:
            secretName: harvester-csi-config
        - hostPath:
            path: /var/lib/kubelet/plugins/kubernetes.io/csi
            type: DirectoryOrCreate
          name: kubernetes-csi-dir
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
          name: registration-dir
        - hostPath:
            path: /var/lib/kubelet/harvester-plugins/driver.harvesterhci.io
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
          name: pods-mount-dir
        - hostPath:
            path: /dev
          name: host-dev
        - hostPath:
            path: /sys
          name: host-sys
        - hostPath:
            path: /
          name: host
        - hostPath:
            path: /lib/modules
          name: lib-modules
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: harvester-csi
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: harvester-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: harvester-csi
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-controller
  template:
    metadata:
      labels:
        app: csi-controller
    spec:
      containers:
        - args:
            - --v=5
            - --csi-address=$(ADDRESS)
            - --csiTimeout=2m5s
            - --leader-election
            - --leader-election-namespace=$(POD_NAMESPACE)
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: longhornio/csi-resizer:v0.5.1-lh1
          name: csi-resizer
          volumeMounts:
            - mountPath: /csi/
              name: socket-dir
        - args:
            - --v=5
            - --csi-address=$(ADDRESS)
            - --timeout=2m5s
            - --enable-leader-election
            - --leader-election-type=leases
            - --leader-election-namespace=$(POD_NAMESPACE)
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: longhornio/csi-provisioner:v1.6.0-lh1
          name: csi-provisioner
          volumeMounts:
            - mountPath: /csi/
              name: socket-dir
        - args:
            - --v=5
            - --csi-address=$(ADDRESS)
            - --timeout=2m5s
            - --leader-election
            - --leader-election-namespace=$(POD_NAMESPACE)
            - --default-fstype=ext4
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: longhornio/csi-attacher:v2.2.1-lh1
          name: csi-attacher
          volumeMounts:
            - mountPath: /csi/
              name: socket-dir
      serviceAccountName: harvester-csi
      tolerations:
        - effect: NoSchedule
          key: kubevirt.io/drain
          operator: Exists
      volumes:
        - hostPath:
            path: /var/lib/kubelet/harvester-plugins/driver.harvesterhci.io
            type: DirectoryOrCreate
          name: socket-dir
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: driver.harvesterhci.io
spec:
  attachRequired: true
  fsGroupPolicy: ReadWriteOnceWithFSType
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: harvester
allowVolumeExpansion: true
provisioner: driver.harvesterhci.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
