---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.5.8
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: docker-publish-master
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/harvester-csi-driver"
    tag: "master-head-linux-amd64"
    username:
      from_secret: docker_username
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      - refs/heads/master
    event:
      - push

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/harvester-csi-driver"
    tag: "${DRONE_TAG}-linux-amd64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: rancher/dapper:v0.5.8
    commands:
      - dapper ci
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: docker-publish-master
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: "rancher/harvester-csi-driver"
      tag: "master-head-linux-arm64"
      username:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/heads/master
      event:
        - push

  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: package/Dockerfile
      password:
        from_secret: docker_password
      repo: "rancher/harvester-csi-driver"
      tag: "${DRONE_TAG}-linux-arm64"
      username:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
---
kind: pipeline
name: manifest

steps:
  - name: push-manifest-head
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: "rancher/harvester-csi-driver:${DRONE_BRANCH}-head"
      template: "rancher/harvester-csi-driver:${DRONE_BRANCH}-head-OS-ARCH"
      ignore_missing: true
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      ref:
        include:
          - refs/heads/master
          - refs/heads/release/v*
      event:
        - push

  - name: push-manifest-tag
    image: plugins/manifest
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      target: "rancher/harvester-csi-driver:${DRONE_TAG}"
      template: "rancher/harvester-csi-driver:${DRONE_TAG}-OS-ARCH"
      ignore_missing: true
      platforms:
        - linux/amd64
        - linux/arm64
    when:
      ref:
        include:
          - refs/head/master
          - refs/tags/*
      event:
        - tag

depends_on:
  - amd64
  - arm64