#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
if [ "$(uname)" = "Linux" ]; then
    OTHER_LINKFLAGS="-extldflags -static -s"
fi
LINKFLAGS="-X github.com/harvester/harvester-csi-driver/pkg/version.Version=$VERSION"
LINKFLAGS="-X github.com/harvester/harvester-csi-driver/pkg/version.GitCommit=$COMMIT $LINKFLAGS"

for arch in "amd64" "arm64"; do
    GOARCH="$arch" CGO_ENABLED=0 go build -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o bin/harvester-csi-driver-"$arch"
done
